# Generated by Django 3.0.2 on 2020-01-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_project', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('r_description', models.TextField(blank=True, verbose_name='Descrição do Projeto')),
                ('r_create_project', models.DateTimeField(auto_now_add=True)),
                ('r_update_project', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_volts', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RTypeCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_ckt', models.CharField(max_length=50, verbose_name='Tipo de Circuito')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencDimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_local', models.CharField(max_length=50, verbose_name='Local da Instalação')),
                ('r_numbers_points', models.IntegerField(verbose_name='Quantidade')),
                ('r_power_va', models.FloatField(verbose_name='Potência (VA)')),
                ('r_total_power_va', models.FloatField(blank=True, verbose_name='Total (VA)')),
                ('r_current_a', models.FloatField(blank=True, verbose_name='Corrente (A)')),
                ('r_comprimento', models.IntegerField(verbose_name='Comprimento do Circuito (m)')),
                ('r_conductor_session', models.CharField(blank=True, max_length=4, verbose_name='Sessão Transversal do Condutor (mm²)')),
                ('r_volt_drop_allow', models.FloatField(verbose_name='Queda de Tensão Permitida (%)')),
                ('r_numero_polos', models.IntegerField(verbose_name='Número de Polos')),
                ('r_nominal_chain', models.IntegerField(blank=True, max_length=4, verbose_name='Corrente Nominal')),
                ('r_appl_circ_break', models.CharField(blank=True, max_length=3, verbose_name='Verifica Disjuntor')),
                ('r_create_circuit', models.DateTimeField(auto_now_add=True)),
                ('r_update_circuit', models.DateTimeField(auto_now=True)),
                ('r_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.RProject', verbose_name='Nome do Projeto')),
                ('r_tension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.RTension', verbose_name='Tensão (VA)')),
                ('r_type_circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.RTypeCircuit', verbose_name='Tipo de Instalação')),
            ],
        ),
    ]
