# Generated by Django 3.0.2 on 2020-01-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='r_nominal_chain',
            field=models.IntegerField(blank=True, verbose_name='Corrente Nominal'),
        ),
    ]
