# Generated by Django 3.0.2 on 2020-01-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0002_auto_20200127_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencdimens',
            old_name='r_comprimento',
            new_name='r_circuit_length',
        ),
    ]
