# Generated by Django 3.0.2 on 2020-01-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0003_auto_20200127_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencdimens',
            old_name='r_projeto',
            new_name='r_project',
        ),
    ]
