# Generated by Django 3.0.2 on 2020-01-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0007_residencdimens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='r_project',
            field=models.CharField(max_length=50, verbose_name='Nome do Projeto'),
        ),
    ]
