# Generated by Django 3.0.2 on 2020-01-31 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0008_auto_20200131_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='r_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.RProject', verbose_name='Nome do Projeto'),
        ),
    ]
