# Generated by Django 3.0.2 on 2020-01-13 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalatioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_instalation', models.CharField(max_length=30, verbose_name='Tipo de Instalação')),
            ],
        ),
        migrations.CreateModel(
            name='IsolatioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_isolation', models.CharField(max_length=3, verbose_name='Tipo de Isolação')),
            ],
        ),
        migrations.CreateModel(
            name='CableCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_polos', models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Número de Polos')),
                ('corrente_ckt', models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Número de Polos')),
                ('instalation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calc.InstalatioType', verbose_name='Tipo de Instalação')),
                ('isolation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calc.IsolatioType', verbose_name='Tipo de Isolação')),
            ],
        ),
    ]
