# Generated by Django 3.0.2 on 2020-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablecalculator',
            name='corrente_ckt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Corrente Total'),
        ),
    ]
