# Generated by Django 3.0.2 on 2020-01-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200118_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tension', models.CharField(max_length=4, verbose_name='Tipo de Tenção')),
            ],
        ),
        migrations.AddField(
            model_name='cablecalculator',
            name='tension',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Tension', verbose_name='Tipo de Tenção'),
            preserve_default=False,
        ),
    ]
