# Generated by Django 3.0.2 on 2020-01-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200118_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablecalculator',
            name='corrente_ckt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Potência do CKT'),
        ),
        migrations.AlterField(
            model_name='cablecalculator',
            name='tension',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Tension', verbose_name='Tipo de Tensão'),
        ),
    ]
